# Configuración base compartida
services:
  db:
    image: postgres:15-alpine
    container_name: inventario_db_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - inventario_pg_data:/var/lib/postgresql/data
      - ./basededatos/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - inventory_network

  backend:
    build:
      context: ./backend
    container_name: inventario_backend_container
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - inventory_network

  frontend:
    container_name: inventario_frontend_container
    networks:
      - inventory_network

volumes:
  inventario_pg_data:

networks:
  inventory_network:
    driver: bridge
